#!/usr/bin/env python3
"""
Wiki Master Builder (The Librarian)
Global Synthesis & Governance for SkillsBuilder LLM Wiki
"""

import os
import json
import re
import sys
import io
from datetime import datetime
from email_analyzer import EmailAnalyzer

# Fix Windows encoding
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

WIKI_DIR = 'wiki'
INDEX_FILE = os.path.join(WIKI_DIR, 'index.md')

def extract_frontmatter(content):
    """Extract YAML frontmatter from markdown content."""
    match = re.search(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
    if match:
        yaml_text = match.group(1)
        # Simple parser for the specific format we use
        data = {}
        for line in yaml_text.split('\n'):
            if ':' in line:
                key, val = line.split(':', 1)
                data[key.strip()] = val.strip().strip('"').strip("'")
        return data
    return {}

def scan_wiki():
    """Scan all wiki files and build a registry of metadata."""
    registry = []
    for root, dirs, files in os.walk(WIKI_DIR):
        for f in files:
            if f.endswith('.md') and f.lower() not in ['index.md', 'log.md', '.processed_emails.txt']:
                filepath = os.path.join(root, f)
                with open(filepath, 'r', encoding='utf-8') as file:
                    content = file.read()
                    meta = extract_frontmatter(content)
                    meta['file'] = os.path.relpath(filepath, WIKI_DIR).replace('\\', '/')
                    meta['title'] = meta.get('title', f.replace('.md', ''))
                    registry.append(meta)
    return registry

def generate_global_index(registry):
    """Generate a structured index.md."""
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    sections = {
        'projects': '🏗️ Projects',
        'org': '🏢 Organizations',
        'artifact': '📄 Artifacts & Reports',
        'domain': '🧠 Technical Domains',
        'quality': '🛠️ Improvements (CAPA)',
        'lifecycle': '🔄 Lifecycle (PDCA)'
    }
    
    content = f"# SkillsBuilder Knowledge Index\n\n"
    content += f"> Last Global Synthesis: {now}\n\n"
    
    # Critical Items Section
    critical = [m for m in registry if m.get('urgency') == 'critical']
    if critical:
        content += "## 🚨 Critical Focus Items\n"
        for m in critical:
            content += f"- [[{m['file']}|{m['title']}]] ({m.get('type', 'event')})\n"
        content += "\n"

    # Category Sections
    for cat, title in sections.items():
        items = [m for m in registry if m.get('type') == cat]
        if items:
            content += f"## {title}\n"
            for m in items[:15]: # Limit to 15 per section in index
                content += f"- [[{m['file']}|{m['title']}]]\n"
            if len(items) > 15:
                content += f"  *... and {len(items)-15} more*\n"
            content += "\n"

    with open(INDEX_FILE, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"✅ Global Index generated at {INDEX_FILE}")

def generate_global_insights(registry, analyzer):
    """Generate high-level synthesized reports (Karpathy's 3rd Layer: Knowledge Products)."""
    print("🧠 Generating Global Insights...")
    
    # 1. Identify Critical CAPA (Quality Alerts)
    critical_capa = [m for m in registry if m.get('type') == 'quality' and m.get('urgency') in ['critical', 'high']]
    
    # 2. Identify Active Projects
    active_projects = [m for m in registry if m.get('type') == 'project' and m.get('lifecycle') in ['do', 'check']]
    
    insight_content = f"# Operational Intelligence Report\n\n"
    insight_content += f"> Generated by SkillsBuilder Librarian on {datetime.now().strftime('%Y-%m-%d')}\n\n"
    
    insight_content += "## 📈 Project Velocity & Health\n"
    if active_projects:
        insight_content += f"Currently tracking **{len(active_projects)}** active projects in execution/validation phases.\n"
        for p in active_projects[:5]:
            insight_content += f"- [[{p['file']}|{p['title']}]] (Phase: {p['lifecycle'].upper()})\n"
    else:
        insight_content += "No active execution-phase projects detected.\n"
    
    insight_content += "\n## ⚠️ Quality & CAPA Risk Assessment\n"
    if critical_capa:
        insight_content += f"DETECTED **{len(critical_capa)}** high-priority quality issues requiring immediate attention.\n"
        for c in critical_capa:
            insight_content += f"- [[{c['file']}|{c['title']}]] (Urgency: {c['urgency'].upper()})\n"
    else:
        insight_content += "Quality metrics appear stable based on current wiki evidence.\n"

    # Synthesis Prompt for Global Trends
    print("   -> Synthesizing global trends via AI...")
    global_context = f"Active Projects: {len(active_projects)}\nCritical Issues: {len(critical_capa)}\nRecent Entities: {len(registry)}"
    prompt = f"As a Senior Industrial Architect, analyze this knowledge base snapshot and provide 3 strategic recommendations for the management team.\n\nSnapshot:\n{global_context}"
    
    recommendations = analyzer.call_ai(prompt, "You are a strategic industrial consultant.")
    
    insight_content += "\n## 💡 AI Strategic Recommendations\n"
    insight_content += recommendations
    
    report_path = os.path.join(WIKI_DIR, 'insights', 'Operational_Intelligence.md')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(insight_content)
    print(f"✨ Global Insights generated at {report_path}")

def run_global_synthesis():
    print("🚀 Starting Global Synthesis...")
    analyzer = EmailAnalyzer()
    registry = scan_wiki()
    print(f"Found {len(registry)} knowledge entities.")
    
    generate_global_index(registry)
    generate_global_insights(registry, analyzer)
    
    print("✨ Global Synthesis Complete.")

if __name__ == "__main__":
    run_global_synthesis()
